solved various problems related to cmd2
and trying to speed up the mapping phase a bit. The change was motivated
by set_value being deprecated so I moved to loc/iloc solutions.
There must remain some process while scoring packets, todo at least it
should print a warning or debug for unknown fields.

Now needs to tune up the reindex process:
  File "/nix/store/4gv4gk5mq055dh0nrhj982yl02pzcfja-python3.6-pandas-0.21.0/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2684, in get_indexer
    raise InvalidIndexError('Reindexing only valid with uniquely'
pandas.core.indexes.base.InvalidIndexError: Reindexing only valid with uniquely valued Index objects