Summayr_extended fails with a division by 0
might be because one is merged and not the other: check use of _first/_second

TcpUnidirectionalStats(tcpstreamid=0, throughput_bytes=0, tcp_goodput=nan, mptcp_goodput_bytes=3, throughput_contribution=None, goodput_contribution=None)
TcpUnidirectionalStats(tcpstreamid=1, throughput_bytes=0, tcp_goodput=nan, mptcp_goodput_bytes=109, throughput_contribution=None, goodput_contribution=None)
TcpUnidirectionalStats(tcpstreamid=2, throughput_bytes=0, tcp_goodput=nan, mptcp_goodput_bytes=0, throughput_contribution=None, goodput_contribution=None)
TcpUnidirectionalStats(tcpstreamid=3, throughput_bytes=0, tcp_goodput=nan, mptcp_goodput_bytes=0, throughput_contribution=None, goodput_contribution=None)

DEBUG:root:4 reinjected packets
DEBUG:root:3 reinjected packets
MATT mptcp throughput  0
DEBUG:mptcpanalyzer.statistics:for tcpstream 0
Traceback (most recent call last):
  File "/nix/store/7hyvk389087apnvkdqmcqscjpsqd22mz-python3.7-cmd2-0.9.7/lib/python3.7/site-packages/cmd2/cmd2.py", line 1716, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/nix/store/7hyvk389087apnvkdqmcqscjpsqd22mz-python3.7-cmd2-0.9.7/lib/python3.7/site-packages/cmd2/cmd2.py", line 2003, in onecmd
    stop = func(statement)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/parser.py", line 153, in cmd_wrapper
    return func(instance, args, unknown) # type:ignore
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 705, in do_summary_extended
    destination=destination
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/statistics.py", line 215, in mptcp_compute_throughput_extended
    sf.throughput_contribution = sf_mptcp_throughput/stats.mptcp_throughput_bytes
ZeroDivisionError: division by zero
EXCEPTION of type 'ZeroDivisionError' occurred with message: 'division by zero'